"""Creating song.file_id'

Revision ID: db7e74d62b7a
Revises: 7aaf444f926b
Create Date: 2023-12-10 23:46:34.069222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7e74d62b7a'
down_revision: Union[str, None] = '7aaf444f926b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('file_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'file_id')
    # ### end Alembic commands ###
